-- Create Appointments table
create table appointments (
  id bigint generated by default as identity primary key,
  created_at timestamp within time zone default timezone('utc'::text, now()) not null,
  date date not null,
  product_id bigint references products(id) not null,
  units numeric not null default 1,
  total_cost numeric not null,
  status text default 'pending' check (status in ('pending', 'confirmed', 'completed', 'cancelled'))
);

-- RLS Policies (Simple for now, matching existing pattern)
alter table appointments enable row level security;

create policy "Enable all access for all users" on appointments
for all using (true) with check (true);
